### ISSUE TITLE
Share Pixmaps Altcoin logo Icon with unelmacoin and  Altcoin Blockchain C++ Project

### ISSUE THREAD

**Issue by francoDeveloper1** [unelmacoin/unelmacoin#1]

**Comment by francoDeveloper1** [comment]
![ALTCOIN_LOGO](https://user-images.githubusercontent.com/82907763/117458562-46a45380-aeff-11eb-9659-fde2a4fdd01f.jpg)

**Comment by unelmacoin** [comment]
This is not the right unelmacoin logo so closing the issue. Please reopen with right one.
